return {
  format = 1,
  name = "default",
  version = "0.1.0",
  app = { id = "openecs.default", name = "OpenECS" },
  depends = { sketch_c = "0.1", sketch_lua = "0.1" },
  settings = { ["sketch_c.brush_color"] = "red", ["sketch_lua.brush_color"] = "green" },
  keys = { ["Ctrl+Tab"] = "sketch_c.next_workspace" },
  workspaces = {
    { name = "C",
      windows = {
        { split = "horizontal",
          { share = 3, panels = { { type = "sketch_c.canvas" } } },
          { size = 260, panels = { { type = "sketch_c.clock" } } },
        },
      },
    },
    { name = "Lua",
      keys = { ["Ctrl+Tab"] = "sketch_lua.next_workspace" },
      windows = {
        { split = "horizontal",
          { share = 3, panels = { { type = "sketch_lua.canvas" } } },
          { size = 260, panels = { { type = "sketch_lua.clock" } } },
        },
      },
    },
    { name = "Side by side",
      windows = {
        { split = "vertical",
          { share = 3, split = "horizontal",
            { panels = { { type = "sketch_c.canvas" } } },
            { panels = { { type = "sketch_lua.canvas" } } },
          },
          { share = 1, panels = { { type = "sketch_c.clock" }, { type = "sketch_lua.clock" } } },
        },
      },
    },
  },
}
